services:
  pythonapp:
    build: ./python/
    depends_on:
      mysql:
        condition: service_healthy
    volumes: ['./python:/code', './secrets:/secrets'] 
    environment:
      API_KEY_FILE: ./secrets/opendota_key.txt
    secrets:
      - opendota_key

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_USER: webapp
      MYSQL_PASSWORD_FILE: /run/secrets/secret_db_pw
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secret_db_root_pw
    ports:
      - '3306:3306' 
    secrets:
      - secret_db_pw
      - secret_db_root_pw
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10

secrets:
  secret_db_pw:
    file: ./secrets/db_password.txt
  secret_db_root_pw:
    file: ./secrets/db_root_password.txt
  opendota_key:
    file: ./secrets/opendota_key.txt
  discord_test_token:
    file: ./secrets/discord_test_token.txt